sudo: true
go: "1.11"
services:
  - docker
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
script:
  - dep ensure -vendor-only
  - go test
  - docker build -t travisci/macbot .
deploy:
  provider: script
  script: bin/docker-push
  on:
    branch: master
notifications:
  email: false
